In [12]:
import numpy
world_alcohol = numpy.genfromtxt("Z:/downloads/机器学习/天善学院/唐宇迪-2-21/numpy/world_alcohol.txt",delimiter=",",dtype=str,skip_header=1)
print(type(world_alcohol))
print(world_alcohol)

<class 'numpy.ndarray'>
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [10]:
import numpy 
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print (vector)
print (matrix)
print (vector.shape)
print (matrix.shape)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(4,)
(3, 3)


In [23]:
import numpy 
company = numpy.array(['b','m','j','c','b','c','b'])
print(company)
company=[chr(ord(letter)-1) for letter in company]
print(company)

['b' 'm' 'j' 'c' 'b' 'c' 'b']
['a', 'l', 'i', 'b', 'a', 'b', 'a']


In [1]:
a = 'a'
print(ord(a))
print(chr(ord(a)+1))

97
b
